name: shoppingmall
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # 여기에 추가적인 자산이 필요하다면 주석을 제거하고 사용하세요.
    # - assets/images/a_dot_burr.jpeg
    # - assets/images/a_dot_ham.jpeg

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
